### PR TITLE
added action helper with readme examples and tests.

### PR DESCRIPTION
**Pull request by elorest**
Wrote tests and changed readme for this issue. https://github.com/drujensen/kemalyst/issues/33

I also added syntax highlighting in readme.

### CODE REVIEW

**Review by drujensen — APPROVED** [review]
This is great!  I will look at updating kemalyst-generator templates with this.  :+1:

**Comment by elorest** [comment]
I was already working on that. Do you work with the guy who maintains that?

**Comment by drujensen** [comment]
go for it!  I will release when your done.

**Comment by elorest** [comment]
I submitted that PR so I I'll just wait for it to be accepted.
https://github.com/TechMagister/kemalyst-generator/pull/31

It doesn't currently work though because the only way to use the code from this pull request is to point 
```yaml
kemalyst:
  branch: master
```

**Comment by elorest** [comment]
Mysql migrations don't work when generated so I'll try to fix that too. I know how to fix it but don't want to break it for postgres so I'll probably have to separate some of the logic.

**Pull request merged**
