### PR TITLE
Move to crack

### PR DESCRIPTION
**Pull request by drujensen**
This PR moves the common set of handlers to their own project.  This will allow them to be re-used in other frameworks like Kemal or on their own.

### CODE REVIEW

**Comment by elorest** [comment]
Because the router depends on params being parsed in order to get `params["_method"]` I don't think that params handler should be moved into a separate project. In my opinion only optional handlers should be moved out.

**Comment by drujensen** [comment]
@elorest hmmm.  Agree there shouldn't be a dependency.  Maybe I should remove the params["_method"] from the router and create a new handler for it? Or maybe your right and params should stay in Kemalyst.

**Comment by elorest** [comment]
I would argue that all restful methods need to work in the router by
default. Also I don't think we want to parse params twice.

**Comment by drujensen** [comment]
right, right.  The method override is because HTML 4/5 doesn't support PUT and DELETE.  Any AJAX call should work fine for these RESTful endpoints.  I created a new handler called `Method` that handles the HTML method override and will be added to the stack by default.  This is how rack does it.  This will remove the dependency and move it to crack.

**Pull request merged**
