### PR TITLE
added support for multipart forms

### PR DESCRIPTION
**Pull request by elorest**
I ran a `crystal tool format` but didn't expect it to effect so many files. 

Anyway the files you should be looking at are context.cr, file_upload.cr, and params.cr.
This should resolve this issue. https://github.com/drujensen/kemalyst/issues/37

### CODE REVIEW

**Review by drujensen — APPROVED** [review]
:+1:

**Comment by elorest** [comment]
Do you have any suggestions how to test multipart form data? I can't seem to get it working in a similar way to how you tested queries and url_encoded forms.

**Comment by drujensen** [comment]
I will take a look at it...

**Comment by elorest** [comment]
Interestingly Kemal doesn't seem to have specs for it either.

**Pull request merged**
